# Generated by Django 5.2.7 on 2025-10-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='Ordem de Serviço', max_length=100, verbose_name='Título da OS'),
        ),
    ]
