# Generated by Django 5.2.7 on 2025-10-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_workorder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Título da OS'),
        ),
    ]
