# Generated by Django 5.2.7 on 2025-10-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_workorder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='customer_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
