# Generated by Django 5.2.7 on 2025-11-02 01:18

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_workorder_customer_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Tempo estimado por unidade do serviço (em minutos).', verbose_name='Tempo padrão (min)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='default_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço padrão'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='workitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço unitário'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fechamento'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='customer_confirmed',
            field=models.BooleanField(default=False, verbose_name='Confirmada pelo cliente'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='opened_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Abertura'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('open', 'Aberta'), ('in_progress', 'Em execução'), ('done', 'Concluída'), ('canceled', 'Cancelada')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
