# Generated by Django 5.2.7 on 2025-11-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='estimated_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Tempo estimado do serviço em minutos', verbose_name='Tempo padrão (min)'),
        ),
    ]
